### ISSUE TITLE
App crash when try to open pdf file

### ISSUE THREAD

**Issue by waqas-ahmad762** [crazecoder/open_file#179] opened 2022-02-07 06:59 UTC
When I am using open_file package with google_sign_in and google_maps_flutter. IOS app crash. If I uncomment both of these 2 packages everything works fine. 

Packages I am using
google_maps_flutter: ^2.1.1
google_sign_in: ^5.2.3
open_file: ^3.2.0

[flutter doctor output.txt](https://github.com/crazecoder/open_file/files/8012996/flutter.doctor.output.txt)

Code to open file
`static Future openFile(File file) async {
    final url = file.path;
    print(url);
    await OpenFile.open(url);
  }`

**Comment by JulianBissekkou** [comment] 2022-03-08 07:50
I have the same issue. 
This is probably a duplicate of #167

**Comment by JulianBissekkou** [comment] 2022-03-08 08:25
The following exception is thrown:

```
Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[2]'
```

**Comment by waqas-ahmad762** [comment] 2022-03-08 11:45
@JulianBissekkou I face this issue only in debug build. In the release build, everything works fine on my side.

**Comment by JulianBissekkou** [comment] 2022-08-01 05:22
It would be nice if this also works in debug mode. This slows down development since you have to test every change related with this plugin in release mode.

**Comment by crazecoder** [comment] 2024-10-06 09:52
Because it is too old, if the new version still has this problem, please let me know

**Closed by crazecoder** 2024-10-06 09:52 UTC
