### ISSUE TITLE
A function declaration without a prototype is deprecated in all versions of C

### ISSUE THREAD

**Issue by mr-slonn** [crazecoder/open_file#308] opened 2024-10-18 11:49 UTC
When building for iOS 15, I receive the following notification:

static UIViewController *RootViewController() {
/.pub-cache/hosted/pub.dev/open_filex-4.5.0/ios/Classes/OpenFilePlugin.m:10:44 A function declaration without a prototype is deprecated in all versions of C

**Comment by crazecoder** [comment] 2024-10-18 11:59
duplicate of #307

**Closed by crazecoder** 2024-10-18 11:59 UTC
