### ISSUE TITLE
Not Work on android After installing release build 

### ISSUE THREAD

**Issue by abdulrehmananwar** [crazecoder/open_file#122] opened 2021-01-15 11:27 UTC
when i run flutter build apk-release this error shows

D:\flutter\.pub-cache\hosted\pub.dartlang.org\open_file-3.0.3\android\src\main\java\com\crazecoder\openfile\OpenFilePlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details

**Comment by crazecoder** [comment] 2021-04-19 09:21
duplicate of #140

**Closed by crazecoder** 2021-04-19 09:21 UTC
