### ISSUE TITLE
Not able to open  file from the assets folder of my app

### ISSUE THREAD

**Issue by SamuraiHub** [crazecoder/open_file#154] opened 2021-07-08 18:53 UTC
It seems not possible to open file from my assets folder in my app. for example this

`OpenFile.open('assets/hello-world.pdf');` 

does not work. Must put the file in a temporary directory before open or there is something else i am missing or a fix for this? Thanks.

**Comment by crazecoder** [comment] 2021-08-04 04:41
duplicate of https://github.com/crazecoder/open_file/issues/98

**Closed by crazecoder** 2021-08-04 04:41 UTC
