### ISSUE TITLE
Cancel

### ISSUE THREAD

**Issue by Cjoshua2** [crazecoder/open_file#168] opened 2021-11-13 03:30 UTC
Is there anyway to identify if the user "cancel" the operation.
for ex: I open the APK file using OpenFile.open() and the user clicks the cancel instead.

I tried the ResultType but it seems like its only for the popup

**Comment by crazecoder** [comment] 2024-08-30 10:32
Duplicate of https://github.com/crazecoder/open_file/issues/189

**Closed by crazecoder** 2024-08-30 10:32 UTC
