### ISSUE TITLE
REQUEST_INSTALL_PACKAGES due google playstore policy

### ISSUE THREAD

**Issue by Boukri** [crazecoder/open_file#222] opened 2022-10-23 01:44 UTC
I can not post any update for my apps in playstore, please update the package ASAP

**Comment by jamesncl** [comment] 2022-10-30 11:03
Duplicate of https://github.com/crazecoder/open_file/issues/204 https://github.com/crazecoder/open_file/issues/221 and https://github.com/crazecoder/open_file/issues/174

The most active issue seems to be Duplicate of https://github.com/crazecoder/open_file/issues/204 there is a lot of discussion there, I suggest you check it out.

Please search the issues list before opening a new one!

**Closed** 2023-01-03 01:59 UTC
