### ISSUE TITLE
Getting error at compile time

### ISSUE THREAD

**Issue by kamleshwebtech** [crazecoder/open_file#133] opened 2021-02-20 06:24 UTC
```
Note: D:\kamlesh\flutter\.pub-cache\hosted\pub.dartlang.org\open_file-3.0.3\android\src\main\java\com\crazecoder\openfile\OpenFilePlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
```

Please suggest how to remove it. Thanks.

**Comment by crazecoder** [comment] 2021-04-17 11:35
duplicate of #140

**Closed by crazecoder** 2021-04-17 11:35 UTC
