### ISSUE TITLE
Open file does nothing, no error, but file doesn't get opened

### ISSUE THREAD

**Issue by herryelbert** [crazecoder/open_file#219] opened 2022-10-10 09:09 UTC
I've been using open_file for quite a while now to open files, but suddenly it doesn't work. I tried altering the code to print out the result of envokeMethod, and this is what shows up in the terminal.
`I/flutter (13494): Result: {"type":-3,"message":"Permission denied: android.Manifest.permission.MANAGE_EXTERNAL_STORAGE"}`

I tried adding the permission MANAGE_EXTERNAL_STORAGE in AndroidManifest.xml, didn't work. I checked my app permission, it has access to file and media. Any help would be greatly appreciated. Thanks.

**Comment by JamesMcIntosh** [comment] 2022-10-13 02:51
Inside `OpenFilePlugin.java` the following code block is the problem.

What I understand is that `MANAGE_EXTERNAL_STORAGE` should not be required as it is seen by Google as a "High risk or sensitive" permission.

It is very unlikely that you will need this permission and will be adequate to have `READ_EXTERNAL_STORAGE `. See the "permitted usages" section for possible use cases.
https://support.google.com/googleplay/android-developer/answer/10467955?hl=en

To fix this problem the following Android R specific code should be removed from `OpenFilePlugin.onMethodCall`
```
public void onMethodCall(MethodCall call, @NonNull Result result) {
...
    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.R) {
        if(!isFileAvailable()){
            return;
        }
        if (!isMediaStorePath()&&!Environment.isExternalStorageManager()) {
            result(-3, "Permission denied: android.Manifest.permission.MANAGE_EXTERNAL_STORAGE");
            return;
        }
    }
...
}
```

**Comment by herryelbert** [comment] 2022-10-13 03:29
Hi @JamesMcIntosh, thanks so much for replying. I actually forgot that I've posted an issue thread here, and yes what you said is correct. After digging for quite some time, I found out that my app's permission only says Media Only even though I asked for Storage permission, after looking for solutions, I found out that MANAGE_EXTERNAL_STORAGE is the problem. But instead of removing the specific code you mentioned, I just asked for both Storage and MANAGE_EXTERNAL_STORAGE, and it seem to work now. I'm not too sure whether this is the best approach though. Should I not ask for MANAGE_EXTERNAL_STORAGE? Oh and also, after asking for that permission, my app's permission changed to All Files instead of Media Only.

**Comment by JamesMcIntosh** [comment] 2022-10-13 04:31
No problem @herryelbert 
You solution will work but if you have a read through the link above then you'll see that it's unlikely that you should be asking for `MANAGE_EXTERNAL_STORAGE`.

**Comment by herryelbert** [comment] 2022-10-13 04:40
I guess you're right, my app is actually ineligible to ask for MANAGE_EXTERNAL_STORAGE, but how to remove that specific code? I can't find OpenFilePlugin.java in my directory.

**Comment by JamesMcIntosh** [comment] 2022-10-13 07:40
OpenFilePlugin.java is part of the Android portion of this library.
Normally what you would do is fork the library and make the change and create a pull request or fork from someone else repository which has the changes you want until this library is updated.
There is already PR #212 looks pretty much what you want.

**Comment by herryelbert** [comment] 2022-10-14 01:13
@JamesMcIntosh Got it working now, I ended up creating another fork. Thanks so much for the help!

**Comment by JamesMcIntosh** [comment] 2022-10-14 02:12
@herryelbert Always happy to help! I would also recommend reopening this ticket until the issue has been fixed in this repository just so that other people can see that the issue is still there.

**Comment by herryelbert** [comment] 2022-10-14 02:26
Ah okay, I'm kinda new to GitHub issues, I thought closing the ticket is just like marking an answer in StackOverflow. I shall do so then, thanks once again.

**Closed** 2023-04-26 11:09 UTC

**Comment by nilsreichardt** [comment] 2023-04-26 12:28
@crazecoder I still have the issue even when I use `open_file` `3.3.0` and I grant permission for `MANAGE_EXTERNAL_STORAGE` (isn't there a different way? this permission is too powerful and for user it's weird that our app needs so much permission for just opening a file) with `await Permission.manageExternalStorage.request()` (using the `permission_handler` package). Why is this issue closed?

**Comment by rj76** [comment] 2023-05-17 07:50
Also stuck with this...

**Comment by sekny** [comment] 2024-07-04 06:32
Your PR is not fix, it working with getTemporaryDirectory but not working with `/storage/emulated/0/Download` directory so the problem is related to open file in that directory
